#!/bin/bash
# ============================================================================
# Stalwart Migration: phasewhip -> RackNerd
# ============================================================================
#
# WHY THIS MIGRATION:
#
#   1. Latency reduction — Stalwart currently runs in an incus container on
#      phasewhip (100.83.112.88). Every email operation from Dustforge on
#      RackNerd (192.3.84.103) crosses Tailscale. Moving Stalwart to the same
#      box as Dustforge drops mail API calls to localhost round-trips.
#
#   2. Security split — With Stalwart on RackNerd, the only inbound dependency
#      on phasewhip is removed. RackNerd becomes fully self-contained for
#      production traffic. Phasewhip stays internal-only (Brain, Conductor,
#      dev work).
#
#   3. Backup architecture — Once phasewhip is free of production mail duties,
#      we repurpose the mail container as a backup puller. It SCPs the Dustforge
#      DB from RackNerd on a cron, giving us an off-site copy with zero new
#      infrastructure.
#
# HOW TO USE THIS SCRIPT:
#   Read each step, run the commands manually, verify before moving on.
#   This is a runbook, not a blind executor.
#
# ============================================================================

set -euo pipefail

echo "============================================================================"
echo "  Stalwart Migration: phasewhip -> RackNerd"
echo "  Run each step manually. Verify before proceeding to the next."
echo "============================================================================"
echo ""

echo "=== Step 1: Install Stalwart on RackNerd ==="
echo ""
echo "SSH to RackNerd:"
echo "  ssh root@192.3.84.103"
echo ""
echo "Install Stalwart:"
echo "  curl -fsSL https://get.stalw.art | sh"
echo ""
echo "Enable and start the service:"
echo "  systemctl enable stalwart"
echo "  systemctl start stalwart"
echo ""
echo "Verify it is listening:"
echo "  ss -tlnp | grep stalwart"
echo ""
echo "NOTE: Stalwart defaults to port 8080 for HTTP admin. If that conflicts"
echo "with Dustforge or other services, reconfigure in /opt/stalwart/etc/config.toml"
echo "before proceeding."
echo ""
echo "---"
echo ""

echo "=== Step 2: Configure Stalwart on RackNerd ==="
echo ""
echo "Copy the Stalwart config from phasewhip as a reference:"
echo "  SSH_ASKPASS=/tmp/ap.sh DISPLAY=dummy setsid ssh claude@100.83.112.88 \\"
echo "    'echo subwayeatfresh | sudo -S incus exec mail -- cat /opt/stalwart/etc/config.toml' \\"
echo "    > /tmp/stalwart-config-reference.toml"
echo ""
echo "Key config to replicate on RackNerd:"
echo "  - Domain: dustforge.com"
echo "  - TLS certificates (use the existing Let's Encrypt certs on RackNerd)"
echo "  - SMTP listener on port 25 (inbound mail)"
echo "  - JMAP/HTTP API port (match what Dustforge .env expects)"
echo "  - Admin credentials"
echo ""
echo "---"
echo ""

echo "=== Step 3: Export accounts and data from phasewhip Stalwart ==="
echo ""
echo "From flimflam, run:"
echo "  # Set up SSH password helper"
echo "  printf '#!/bin/sh\necho subwayeatfresh\n' > /tmp/ap.sh && chmod +x /tmp/ap.sh"
echo ""
echo "  # Export all Stalwart data inside the mail container"
echo "  SSH_ASKPASS=/tmp/ap.sh DISPLAY=dummy setsid ssh claude@100.83.112.88 \\"
echo "    'echo subwayeatfresh | sudo -S incus exec mail -- stalwart-cli export /tmp/stalwart-export'"
echo ""
echo "  # Pull the export to flimflam"
echo "  SSH_ASKPASS=/tmp/ap.sh DISPLAY=dummy setsid scp -r claude@100.83.112.88:/tmp/stalwart-export /tmp/stalwart-export"
echo ""
echo "  NOTE: If the incus container doesn't expose /tmp to the host, you may"
echo "  need to pull files out first:"
echo "    sudo incus file pull -r mail/tmp/stalwart-export /tmp/stalwart-export"
echo ""
echo "---"
echo ""

echo "=== Step 4: Import accounts to RackNerd Stalwart ==="
echo ""
echo "SCP the export to RackNerd:"
echo "  scp -r /tmp/stalwart-export root@192.3.84.103:/tmp/stalwart-export"
echo ""
echo "SSH to RackNerd and import:"
echo "  ssh root@192.3.84.103"
echo "  stalwart-cli import /tmp/stalwart-export"
echo ""
echo "Verify accounts exist:"
echo "  stalwart-cli account list"
echo ""
echo "---"
echo ""

echo "=== Step 5: Update DNS records ==="
echo ""
echo "Ensure these DNS records point to RackNerd (192.3.84.103):"
echo ""
echo "  MX    dustforge.com         -> mail.dustforge.com (priority 10)"
echo "  A     mail.dustforge.com    -> 192.3.84.103"
echo "  TXT   dustforge.com         -> v=spf1 ip4:192.3.84.103 ~all"
echo "  TXT   _dmarc.dustforge.com  -> v=DMARC1; p=quarantine; rua=mailto:postmaster@dustforge.com"
echo ""
echo "DKIM: Generate a new DKIM key on RackNerd Stalwart and update the"
echo "  _domainkey TXT record accordingly."
echo ""
echo "Check current records:"
echo "  dig MX dustforge.com +short"
echo "  dig A mail.dustforge.com +short"
echo ""
echo "---"
echo ""

echo "=== Step 6: Update Dustforge .env on RackNerd ==="
echo ""
echo "Edit /opt/dustforge/.env (or wherever the app env lives):"
echo ""
echo "  Old values (pointing to phasewhip over Tailscale):"
echo "    STALWART_HOST=100.83.112.88"
echo "    STALWART_PORT=8090"
echo ""
echo "  New values (localhost):"
echo "    STALWART_HOST=127.0.0.1"
echo "    STALWART_PORT=8080   # or whatever port Stalwart HTTP API is on"
echo ""
echo "Restart the Dustforge app:"
echo "  systemctl restart dustforge"
echo ""
echo "---"
echo ""

echo "=== Step 7: Test email operations ==="
echo ""
echo "Health check:"
echo "  curl -s https://api.dustforge.com/api/health"
echo ""
echo "Identity lookup (verifies Stalwart connection):"
echo "  curl -s https://api.dustforge.com/api/identity/lookup?username=brain"
echo ""
echo "Send a test email from Brain:"
echo "  # From phasewhip or wherever Brain runs, trigger an email send"
echo "  # and verify it arrives at an external mailbox."
echo ""
echo "Receive a test email:"
echo "  # Send an email TO brain@dustforge.com from an external address"
echo "  # and verify it lands in the Stalwart mailbox on RackNerd."
echo ""
echo "Check Stalwart logs for errors:"
echo "  journalctl -u stalwart -f --no-pager -n 50"
echo ""
echo "---"
echo ""

echo "=== Step 8: Repurpose phasewhip mail container ==="
echo ""
echo "Once RackNerd Stalwart is confirmed working:"
echo ""
echo "Stop Stalwart on phasewhip:"
echo "  SSH_ASKPASS=/tmp/ap.sh DISPLAY=dummy setsid ssh claude@100.83.112.88 \\"
echo "    'echo subwayeatfresh | sudo -S incus exec mail -- systemctl stop stalwart'"
echo "  SSH_ASKPASS=/tmp/ap.sh DISPLAY=dummy setsid ssh claude@100.83.112.88 \\"
echo "    'echo subwayeatfresh | sudo -S incus exec mail -- systemctl disable stalwart'"
echo ""
echo "Install backup puller cron in the mail container (repurposed as backup node):"
echo "  # Add to crontab:"
echo "  0 */6 * * * scp root@192.3.84.103:/opt/dustforge/data/dustforge.db /backups/dustforge-\$(date +\\%Y\\%m\\%d-\\%H\\%M).db"
echo ""
echo "  # Retention cleanup (keep 14 days):"
echo "  30 0 * * * find /backups -name 'dustforge-*.db' -mtime +14 -delete"
echo ""
echo "This gives us off-site DB backups on phasewhip every 6 hours,"
echo "complementing the on-box daily backups already running on RackNerd."
echo ""
echo "---"
echo ""

echo "=== Step 9: Final verification ==="
echo ""
echo "Checklist:"
echo "  [ ] Stalwart running on RackNerd (systemctl status stalwart)"
echo "  [ ] All accounts imported and accessible"
echo "  [ ] Dustforge .env updated to localhost Stalwart"
echo "  [ ] Dustforge app restarted and healthy"
echo "  [ ] DNS MX/A/SPF/DKIM/DMARC records updated"
echo "  [ ] Inbound email delivery tested"
echo "  [ ] Outbound email delivery tested"
echo "  [ ] Stalwart stopped on phasewhip"
echo "  [ ] Backup puller cron installed on phasewhip"
echo "  [ ] Old Stalwart export cleaned up from /tmp on all machines"
echo ""
echo "============================================================================"
echo "  Migration complete. RackNerd is now self-contained for production."
echo "============================================================================"
